### ISSUE TITLE
Pool token address mismatch 

### ISSUE THREAD

**Issue by yurenji** [project-serum/oyster-swap#22]
![image](https://user-images.githubusercontent.com/5565266/100853985-5e485d80-34c3-11eb-9a54-0c56ff25f671.png)

The USDT and Sushi token address is mismatched, if you click the link it takes u to the other token. 

**If someone just copy/paste the address, it may cause problem, though I am not sure how big the damage can be.**

**Comment by yamijuan** [comment]
Working on it, I was able to reproduce it by swaping the tokens inputs, that doesnt change the addresses
