### ISSUE TITLE
Swap button keep spinning 

### ISSUE THREAD

**Issue by yurenji** [project-serum/oyster-swap#27]
![swap-bug](https://user-images.githubusercontent.com/5565266/101459108-c50dc100-3972-11eb-9a3a-71af4efb5b6e.gif)

It just keeps spinning after clicking Swap. I tried different trade pairs, it's the same behavior. 

(I have enough balance and about 10 SOL in my wallet. )

**Comment by euclidestesticle** [comment]
Hello Yurenji, can you dm me on discord please: Tristan#7679 happy to troubleshoot there

**Comment by yurenji** [comment]
> Hello Yurenji, can you dm me on discord please: Tristan#7679 happy to troubleshoot there

sure. sent you msg on discord. close this issue for now.
